import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import Navbar from '@/components/Navbar';

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Commune de Beuvardes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        <Navbar />
        <div className={styles.home__container}>

          <div className={styles.home__left}></div>
          <div className={styles.home__right}></div>
        </div>
      </div>
    </>
  )
}

export default Home;